# !/bin/python3

MAX_NODES = 256
TIMEOUT = None

ROUNDS = 5 ################

REDUCTION_TWO = 2

tou_prop = MAX_NODES * 0.05

tou_step = MAX_NODES * 0.2

tou_final = MAX_NODES * 0.2

FINAL_STEP  = 1000000

MAX_STEPS = 10 # given in the problem statement

PRIORITY_GOSSIP_TIMEOUT = 3
BLOCK_PROPOSE_GOSSIP_TIMEOUT	= 3
BLOCK_VOTE_REDUCTION_S1_GOSSIP_TIMEOUT = 20 # TODO check once
BLOCK_VOTE_REDUCTION_S2_GOSSIP_TIMEOUT = 20 # TODO check once
BA_STAR_GOSSIP_TIMEOUT = 20 # TODO check
TIMEOUT_NOT_APPLICABLE = -1
MAX_ALGORAND = 50
GENESIS_BLOCK_CONTENT = "We are building the best Algorand Discrete Event Simulator"

# max(MIN_DELAY,normal_delay)/DIVIDE_BY
MIN_DELAY = 0
DIVIDE_BY = 1000


TENTATIVE_CONSENSUS		 	= "tentative"
FINAL_CONSENSUS		 		= "final"
NO_CONSENSUS		 		= "no_consensus"

GOSSIP_FAN_OUT 			= 10
T_STEP_REDUCTION_STEP_ONE = 2/3
T_STEP_REDUCTION_STEP_TWO = 2/3


NON_BLOCK_MSG_DELAY_MEAN = 30
NON_BLOCK_MSG_DELAY_SIGMA = 40

BLOCK_MSG_DELAY_MEAN = 200
BLOCK_MSG_DELAY_SIGMA = 400